'use client'
import { ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import { motion } from 'framer-motion'

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-slate-50 dark:bg-gradient-to-br dark:from-slate-950 dark:to-slate-900 text-slate-900 dark:text-white">
            {/* Header */}
            <header className="sticky top-0 z-40 bg-white dark:bg-slate-900/80 dark:backdrop-blur border-b border-slate-200 dark:border-slate-800">
                <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
                    <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Terms & Conditions</h1>
                    <Link href="/login" className="flex items-center gap-2 px-4 py-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                        <ArrowLeft className="w-4 h-4" />
                        Back
                    </Link>
                </div>
            </header>

            {/* Content */}
            <main className="max-w-4xl mx-auto px-6 py-12">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5 }}
                    className="prose dark:prose-invert max-w-none"
                >
                    <p className="text-slate-600 dark:text-slate-400 mb-8">
                        <strong>Last Updated:</strong> 21 June 2026 | <strong>Effective Date:</strong> 21 June 2026
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">1. Acceptance of Terms</h2>
                    <p className="text-slate-700 dark:text-slate-300 mb-4">
                        By accessing or using the Shadow IT Detection System (&quot;System&quot;), you agree to be bound by these Terms and Conditions. If you do not agree, you must not access or use the System.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">2. System Overview</h2>
                    <p className="text-slate-700 dark:text-slate-300 mb-4">
                        The Shadow IT Detection System is an AI-Powered Network Anomaly Detection Framework developed by the Department of Cybersecurity and Information Systems at the University of Mines and Technology, Tarkwa. The System uses an Isolation Forest machine learning model to detect, classify, and profile unauthorized devices and applications on network infrastructure.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">3. User Roles and Access</h2>
                    <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-6 mb-6">
                        <h3 className="font-bold text-slate-900 dark:text-white mb-3">Administrator Role</h3>
                        <p className="text-slate-700 dark:text-slate-300 mb-4">
                            Full access to view, create, update, and delete detection records, alerts, device profiles, and user accounts. Administrators are responsible for system configuration and user management.
                        </p>
                        <h3 className="font-bold text-slate-900 dark:text-white mb-3">Viewer Role</h3>
                        <p className="text-slate-700 dark:text-slate-300">
                            Read-only access to detection results, alert summaries, and device profiles. Viewers cannot modify system data.
                        </p>
                    </div>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">4. Authentication and Security</h2>
                    <p className="text-slate-700 dark:text-slate-300 mb-4">
                        Users must authenticate using valid credentials. Access is controlled through JSON Web Token (JWT) authentication. Sharing credentials is strictly prohibited. You are responsible for maintaining the confidentiality of your login credentials and session tokens.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">5. Permitted Use</h2>
                    <ul className="list-disc list-inside space-y-2 text-slate-700 dark:text-slate-300 mb-6">
                        <li>Monitoring network traffic to detect Shadow IT activity</li>
                        <li>Reviewing and managing alerts generated by the detection model</li>
                        <li>Profiling unauthorised devices and applications</li>
                        <li>Reviewing audit logs for compliance and forensic investigation</li>
                        <li>Academic research and system evaluation</li>
                    </ul>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">6. Prohibited Use</h2>
                    <p className="text-slate-700 dark:text-slate-300 mb-4 font-semibold">Users must not:</p>
                    <ul className="list-disc list-inside space-y-2 text-slate-700 dark:text-slate-300 mb-6">
                        <li>Attempt to bypass authentication or access control mechanisms</li>
                        <li>Access, modify, or delete Audit Log records</li>
                        <li>Conduct unauthorised surveillance or data collection</li>
                        <li>Introduce malicious code or malware into the System</li>
                        <li>Violate applicable laws or regulations (GDPR, HIPAA, CCPA)</li>
                        <li>Share Detection Data with unauthorised third parties</li>
                        <li>Attempt to reverse-engineer or extract source code</li>
                    </ul>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">7. Audit Logging</h2>
                    <p className="text-slate-700 dark:text-slate-300 mb-4">
                        All actions within the System are recorded in a tamper-evident Audit Log. This includes the date, time, action type, resource affected, user identity, source IP, and outcome. The Audit Log is read-only and may be used as evidence in disciplinary or legal proceedings.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">8. Intellectual Property</h2>
                    <p className="text-slate-700 dark:text-slate-300 mb-4">
                        The System, including its source code, machine learning model, dashboard design, and documentation, is the intellectual property of the University of Mines and Technology, Tarkwa. All rights are reserved. No part may be reproduced or used for commercial purposes without express written consent.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">9. Disclaimer of Warranties</h2>
                    <p className="text-slate-700 dark:text-slate-300 mb-4">
                        The System is provided &quot;as is&quot; for academic and research purposes. We make no warranties regarding the accuracy, completeness, or reliability of Detection Data. The System operates on synthetic data in a simulated environment and should not be relied upon as the sole basis for security decisions without independent verification.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">10. Limitation of Liability</h2>
                    <p className="text-slate-700 dark:text-slate-300 mb-4">
                        To the fullest extent permitted by law, the project team and University shall not be liable for any direct, indirect, or consequential damages arising from the use of or inability to use the System.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">11. Termination of Access</h2>
                    <p className="text-slate-700 dark:text-slate-300 mb-4">
                        Access may be suspended or terminated immediately for breach of these Terms, unauthorised access, misuse, or completion of the academic project. Upon termination, JWT credentials will be revoked and all active sessions invalidated.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">12. Governing Law</h2>
                    <p className="text-slate-700 dark:text-slate-300 mb-4">
                        These Terms are governed by the laws of the Republic of Ghana. Any disputes shall be subject to the exclusive jurisdiction of the competent courts of Ghana and the academic governance structures of the University of Mines and Technology, Tarkwa.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">13. Contact Information</h2>
                    <div className="bg-slate-100 dark:bg-slate-800 rounded-lg p-6 mb-8">
                        <p className="text-slate-700 dark:text-slate-300 mb-2"><strong>Project Team:</strong> Shadow IT Detection System</p>
                        <p className="text-slate-700 dark:text-slate-300 mb-2"><strong>Department:</strong> Cybersecurity and Information Systems</p>
                        <p className="text-slate-700 dark:text-slate-300 mb-2"><strong>Institution:</strong> University of Mines and Technology, Tarkwa, Ghana</p>
                        <p className="text-slate-700 dark:text-slate-300"><strong>Supervisor:</strong> Dr. Abdel-Fatao Hamidu</p>
                    </div>

                    <p className="text-center text-slate-500 dark:text-slate-400 text-sm mt-12 py-8 border-t border-slate-200 dark:border-slate-800">
                        © 2026 University of Mines and Technology, Tarkwa. All rights reserved.
                    </p>
                </motion.div>
            </main>
        </div>
    )
}
